### ISSUE TITLE
Bug with ChunkLoadEvent / Wrong minecraft version

### ISSUE THREAD

**Issue by Bubelbub** [IDragonfire/DragonAntiPvPLeaver#25]
Hey guys,

```
2013-03-06 13:23:51 [SEVERE] Could not pass event ChunkLoadEvent to DragonAntiPvPLeaver v1.9.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at net.minecraft.server.v1_4_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:139)
        at net.minecraft.server.v1_4_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:85)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getChunkAt(CraftWorld.java:117)
        at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getChunkAt(CraftWorld.java:493)
        at com.garbagemule.MobArena.region.ArenaRegion.getChunks(ArenaRegion.java:356)
        at com.garbagemule.MobArena.ArenaImpl.removeEntities(ArenaImpl.java:1045)
        at com.garbagemule.MobArena.ArenaImpl.cleanup(ArenaImpl.java:1029)
        at com.garbagemule.MobArena.ArenaImpl.forceEnd(ArenaImpl.java:523)
        at com.garbagemule.MobArena.MobArena.onDisable(MobArena.java:113)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
        at org.bukkit.craftbukkit.v1_4_R1.CraftServer.disablePlugins(CraftServer.java:277)
        at net.minecraft.server.v1_4_R1.MinecraftServer.stop(MinecraftServer.java:351)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:458)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_4_R1.Entity.getBukkitEntity()Lorg/bukkit/entity/Entity;
        at com.topcat.npclib.DragonAntiPvPListener.entity.NPC.getBukkitEntity(NPC.java:45)
        at com.topcat.npclib.DragonAntiPvPListener.NPCManager$WL.onChunkLoad(NPCManager.java:107)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 20 more
```

**Comment by Bubelbub** [comment]
Bug with versions:

http://dev.bukkit.org/server-mods/dragonantipvpleaver/files/9-dragon-anti-pv-pleaver-v1-9-2-r0-1/
http://dev.bukkit.org/server-mods/dragonantipvpleaver/files/9-dragon-anti-pv-pleaver-v1-9/
http://dev.bukkit.org/server-mods/dragonantipvpleaver/files/10-dragon-anti-pvp-leaver-v1-9-3-r0-2/

Bukkit:
Craftbukkit version git-Bukkit-1.4.7-R1.0-b2625jnks (MC: 1.4.7) (Implementing API version 1.4.7-R1.0

**Comment by IDragonfire** [comment]
Did you upgrade bukkit to 1.5 or 1.4 and solve these issue?
