### ISSUE TITLE
Errors running dragonantipvp

### ISSUE THREAD

**Issue by Murdox1221** [IDragonfire/DragonAntiPvPLeaver#28]
Hello, Im currently running a dev build of Spigot 1.6.2 (or Bukkit if you would prefer) Now im having issues with you latest rec build of Dragon. 
here is the error:
http://pastebin.com/092WuKx9

I have ensured that 1.9.6 is the latest version. I have even gone so far as regenerating our files for this. Any help you could provide would be great. This is the only AntiPvplogger that works for our community. 

Thank you
Murdox

**Comment by IDragonfire** [comment]
can you post a little bit more of the log?

**Comment by Murdox1221** [comment]
This is the full for when the server starts
http://pastebin.com/aD1tVLdh

This is ingame. 
http://pastebin.com/a0RfWAvX
Im not sure where one ends and the other begins. But this is after about 5 mins of the server running. We also have MCMMO, which modifies damages, it wasnt an issue before, but maybe it is now. Anyways thanks for your help, and hopefully we can get this worked out.

**Comment by villain79** [comment]
im too use spigot ;/ 

2013-07-15 09:54:14 [INFO] lurase lost connection: disconnect.quitting 2013-07-15 09:54:14 [SEVERE] Could not pass event PlayerQuitEvent to DragonAntiPvPLeaver v1.9.6 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427) at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478) at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463) at net.minecraft.server.v1_6_R2.PlayerList.disconnect(PlayerList.java:260) at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:690) at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:242) at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118) at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37) at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:125) at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592) at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239) at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481) at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413) at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582) Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/FLocation at com.github.idragonfire.DragonAntiPvPLeaver.listener.DAntiPvPLeaverListener.onPlayerQuit(DAntiPvPLeaverListener.java:56) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425) ... 15 more Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.FLocation at java.net.URLClassLoader$1.run(URLClassLoader.java:366) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80) at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 21 more

**Comment by IDragonfire** [comment]
duplicated:
https://github.com/IDragonfire/DragonAntiPvPLeaver/issues/30#issuecomment-22090371
