### ISSUE TITLE
"Silently" catching entity tracking error

### ISSUE THREAD

**Issue by Nicklander** [IDragonfire/DragonAntiPvPLeaver#29]
Hello,

Please help this is spawning my console :

2013-07-20 04:49:06 [SEVERE] "Silently" catching entity tracking error.
2013-07-20 04:49:06 [SEVERE] net.minecraft.server.v1_6_R2.ReportedException: Adding entity to track
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.addEntity(EntityTracker.java:116)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.addEntity(EntityTracker.java:86)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.track(EntityTracker.java:23)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.WorldManager.a(WorldManager.java:18)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.World.a(World.java:957)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.WorldServer.a(WorldServer.java:786)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.World.addEntity(World.java:950)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.World.addEntity(World.java:895)
2013-07-20 04:49:06 [SEVERE]    at com.topcat.npclib.DragonAntiPvPListener.NPCManager$WL.onChunkLoad(NPCManager.java:108)
2013-07-20 04:49:06 [SEVERE]    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
2013-07-20 04:49:06 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-07-20 04:49:06 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:138)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:119)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getBlockAt(CraftWorld.java:83)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getBlockAt(CraftWorld.java:482)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.Location.getBlock(Location.java:82)
2013-07-20 04:49:06 [SEVERE]    at com.topcat.npclib.DragonAntiPvPListener.NPCManager$WL.onChunkLoad(NPCManager.java:106)
2013-07-20 04:49:06 [SEVERE]    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
2013-07-20 04:49:06 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-07-20 04:49:06 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:138)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:84)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getChunkAt(CraftWorld.java:119)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftWorld.getBlockAt(CraftWorld.java:83)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:172)
2013-07-20 04:49:06 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:162)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:610)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.Packet15Place.handle(SourceFile:58)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
2013-07-20 04:49:06 [SEVERE] Caused by: java.lang.IllegalStateException: Entity is already tracked!
2013-07-20 04:49:06 [SEVERE]    at net.minecraft.server.v1_6_R2.EntityTracker.addEntity(EntityTracker.java:96)
2013-07-20 04:49:06 [SEVERE]    ... 46 more

I'm using the newest version of DragonAntiPvPLeaver (1.6.2 on bukkitdev page).
And I'm using craftbukkit build 2815 1.6.2-R0.1.

Keep it up, great plugin :)

**Comment by IDragonfire** [comment]
can you try v1.9.6.2.2882?

or my new beta version:
https://www.dropbox.com/s/tpucubsiijoe3hv/DragonAntiPvPLeaver.jar

**Comment by Nicklander** [comment]
Ok, thank you very much !
I'll try
