### ISSUE TITLE
PlayerQuitEvent

### ISSUE THREAD

**Issue by EnderdragonDe** [IDragonfire/DragonAntiPvPLeaver#30]
Using DragonAntiPvPLeaver v1.9.6.2.2882 and Spigot Build #1049
Whenever a player leaves the game appears this error:

2013-08-04 02:20:43 [INFO] PLAYER lost connection: disconnect.genericReason
2013-08-04 02:20:43 [SEVERE] Could not pass event PlayerQuitEvent to DragonAntiPvPLeaver v1.9.6.2.2882
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:46)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
    at net.minecraft.server.v1_6_R2.PlayerList.disconnect(PlayerList.java:260)
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:688)
    at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:237)
    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
    at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:125)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:592)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:239)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:481)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:413)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/FLocation
    at com.github.idragonfire.DragonAntiPvPLeaver.listener.DAntiPvPLeaverListener.onPlayerQuit(DAntiPvPLeaverListener.java:55)
    at sun.reflect.GeneratedMethodAccessor371.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 15 more

**Comment by IDragonfire** [comment]
Do you use Factions, if yes, which version?

**Comment by EnderdragonDe** [comment]
Factions 2.0.4 MCore 6.5.X
http://dev.bukkit.org/bukkit-plugins/factions/files/58-factions-2-0-4-mcore-6-5-x/

**Comment by IDragonfire** [comment]
Thanks, i dont knew that Factions release a new major version and change the whole API .

**Comment by IDragonfire** [comment]
ok,
can you test these version:

https://www.dropbox.com/s/vsdqgiamizaybys/DragonAntiPvPLeaver.jar

I added factions 2.0 support.

**Comment by villain79** [comment]
so far works well, I'll see tomorrow how it will be more players.

**Comment by IDragonfire** [comment]
_push_

**Comment by IDragonfire** [comment]
_push again_
