### ISSUE TITLE
Error with Permissions?

### ISSUE THREAD

**Issue by Deathmonster555** [IDragonfire/DragonAntiPvPLeaver#38]
When I enable permissions on my server, this error appears. It works fine without permissions so it can't be world guard causing this?

```
10.01 15:51:09 [Multicraft] Deathmonster555 ran command Message of the Day
10.01 15:51:09 [Connect] User Deathmonster555
10.01 15:51:09 [Server] INFO UUID of player Deathmonster555 is 658d3a0b-c45e-40df-af91-964f2bdf02f9
10.01 15:51:04 [Server] INFO Deathmonster555 left the game.
10.01 15:51:04 [Server] INFO ... 11 more
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.listener.Listener_Normal.onPlayerQuit(Listener_Normal.java:56) ~[?:?]
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.SpawnCheckerManager.dragonNpcSpawnTime(SpawnCheckerManager.java:43) ~[?:?]
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.spawnchecker.WorldGuardSupport.canNpcSpawn(WorldGuardSupport.java:28) ~[?:?]
10.01 15:51:04 [Server] INFO Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:130) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:706) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerList.disconnect(PlayerList.java:307) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO org.bukkit.event.EventException
10.01 15:51:04 [Server] ERROR Could not pass event PlayerQuitEvent to DragonAntiPvPLeaver v2.1.7.10
10.01 15:51:04 [Disconnect] User Deathmonster555 has disconnected, reason: Disconnected
```

**Comment by IDragonfire** [comment]
```
10.01 15:51:09 [Multicraft] Deathmonster555 ran command Message of the Day
10.01 15:51:09 [Connect] User Deathmonster555
10.01 15:51:09 [Server] INFO UUID of player Deathmonster555 is 658d3a0b-c45e-40df-af91-964f2bdf02f9
10.01 15:51:04 [Server] INFO Deathmonster555 left the game.
10.01 15:51:04 [Server] INFO ... 11 more
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.listener.Listener_Normal.onPlayerQuit(Listener_Normal.java:56) ~[?:?]
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.SpawnCheckerManager.dragonNpcSpawnTime(SpawnCheckerManager.java:43) ~[?:?]
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.spawnchecker.WorldGuardSupport.canNpcSpawn(WorldGuardSupport.java:28) ~[?:?]
10.01 15:51:04 [Server] INFO Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:130) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:706) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerList.disconnect(PlayerList.java:307) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit-dev-3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
10.01 15:51:04 [Server] INFO org.bukkit.event.EventException
10.01 15:51:04 [Server] ERROR Could not pass event PlayerQuitEvent to DragonAntiPvPLeaver v2.1.7.10
10.01 15:51:04 [Disconnect] User Deathmonster555 has disconnected, reason: Disconnected
´´´

**Comment by IDragonfire** [comment]
WorldGuard hat wohl was an der API geändert ...
Wenn du WorldGuard Support ausschaltest sollte es gehen ...

**Comment by Deathmonster555** [comment]
Yeah, I see it shows that world guard is causing it, but when I disable GroupManager (permissions) This plugin runs fine? are you sure it's worldguard?

**Comment by IDragonfire** [comment]
I said that DAPL supports not the newest  WorldGuard version:

```
10.01 15:51:04 [Server] INFO at com.github.idragonfire.DragonAntiPvPLeaver.spawnchecker.WorldGuardSupport.canNpcSpawn(WorldGuardSupport.java:28) ~[?:?]
10.01 15:51:04 [Server] INFO Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
```

I must look into the WorldGuard code and fix this line:
https://github.com/IDragonfire/DragonAntiPvPLeaver/blob/master/src/com/github/idragonfire/DragonAntiPvPLeaver/spawnchecker/WorldGuardSupport.java#L28

**Comment by Deathmonster555** [comment]
Ok! So, what version does it support? Or should I wait for a fix?

**Comment by IDragonfire** [comment]
What WorldGuard version did you use?

**Comment by Deathmonster555** [comment]
Version 6.0.0-beta-03.1514

**Comment by IDragonfire** [comment]
Yes, it should work with 5.9 ...

**Comment by Deathmonster555** [comment]
Ah ok! Thanks so much! I'll try it out in a bit and let you know

**Comment by Deathmonster555** [comment]
Thank you so much! It finally works!
